# Blog settings
permalink: /blog/:title


name: margarita sokolova 
description: i can computer
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

twitter: ritsok
linkedin: margarita-sokolova
github: ritsok
email: msokolova13@gmail.com
